### PR TITLE
[skip changelog] Sync general formatting check workflow with template

### PR DESCRIPTION
**Pull request by per1234**
**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

Infrastructure update

- **What is the current behavior?**

We have assembled a collection of reusable GitHub Actions workflows:
https://github.com/arduino/tooling-project-assets
These workflows will be used in the repositories of all Arduino tooling projects.

Some minor improvements and standardizations have been made in the upstream "template" workflow, but have not yet been pulled into this repository.

The Prettier formatting tool is used in the tasks for formatting and checking the formatting of the repository's Markdown and YAML files, but its capabilities with other languages are not utilized.

* **What is the new behavior?**

Workflow is synced with the state of the art from upstream.

Prettier formatting is applied to all supported files.

Several of the tasks have been deprecated in favor of the new `general:format-prettier` task:

- `docs:check`
- `docs:format`
- `config:check`
- `config:format`

These still work as before, but they now display a deprecation warning.

- **Does this PR introduce a breaking change, and is
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

>Does this PR introduce a breaking change

No

>is titled accordingly

Yes

* **Other information**:

The "Check Prettier Formatting" workflow run currently fails due to non-compliant formatting in many test data JSON files. With the exception of data that is intentionally non-compliant (e.g., [arduino/libraries/librariesindex/testdata/invalid.json](https://github.com/arduino/arduino-cli/blob/master/arduino/libraries/librariesindex/testdata/invalid.json)), I think it make sense to apply the formatting style even to test data files that are maintained in this repository. The exception would be files that are externally maintained, with the intent to sync their copies in this repository from upstream. I don't have any idea of what the maintenance status is of these files, so I will need input on whether [the `.prettierignore` file](https://prettier.io/docs/en/ignore.html) needs to be expanded.

I would probably submit a separate PR if a significant number of formatting updates are needed, since they are likely better put in a separate commit.

### CODE REVIEW

**Review by umbynos — APPROVED** [review]

**Comment by per1234** [comment]
Since they are the most affected, I'd be interested to get the opinion of @silvanocerza or @cmaglie on this:

>The "Check Prettier Formatting" workflow run currently fails due to non-compliant formatting in many test data JSON files. With the exception of data that is intentionally non-compliant (e.g., `arduino/libraries/librariesindex/testdata/invalid.json`), I think it make sense to apply the formatting style even to test data files that are maintained in this repository. The exception would be files that are externally maintained, with the intent to sync their copies in this repository from upstream. I don't have any idea of what the maintenance status is of these files, so I will need input on whether the `.prettierignore` file needs to be expanded.

**Comment by silvanocerza** [comment]
I think it's ok formatting all files even if they're in a certain sense external, the format must not matter for testing purposes only that they're well formed. So I'd add on `.prettierignore` only those files that are ill formed on purpose and format all the rest. Feel free to format them in a separate commit in this same PR.

Also I think the deprecation warning for the old task commands are not necessary, we can just delete them.

**Comment by per1234** [comment]
>Feel free to format them in a separate commit in this same PR.

OK, will do. Thanks for your feedback.

>I think the deprecation warning for the old task commands are not necessary, we can just delete them.

OK, I will do that then. I wasn't sure whether the removal would be disruptive to anyone's development workflow, but the taskfile is a lot cleaner without a bunch of these deprecated tasks cluttering it up.

**Comment by silvanocerza** [comment]
What's going on with this check? Rerunning didn't help. :thinking: 
https://github.com/arduino/arduino-cli/pull/1380/checks?check_run_id=3281153503

**Comment by per1234** [comment]
Oops, I should have commented about that. I was pretty burned out by the end of the day and had to give it a rest once I hit the unit test failures resulting from the reformatting breaking the index file signature.

The `go.sum` diff is a side effect of Task running the command to generate the `GOLINTBIN` dynamic variable:
https://github.com/arduino/arduino-cli/blob/c44c05aaf4b1bd13ae9ed22ddedd202d31de47a1/Taskfile.yml#L239
It's unintuitive that a workflow that doesn't have anything to do with Go causes this diff, but the `go list` command runs anytime any task is called.

I'm planning to submit a PR to introduce https://github.com/arduino/tooling-project-assets/commit/a98ac6ce766ae4e28d44398e52778b344694079e into the repository later today along with the general sync to the "template" Go check system. That change should sidestep this whole issue. So I think the best approach is to just accept that the "Check Prettier Formatting" workflow will have a spurious failure for a short period rather than wasting time trying to find a solution for a problem that is just going to disappear anyway.

**Comment by silvanocerza** [comment]
Ok, good to know. Am ok with letting this fail for the time being. :+1:

**Review by silvanocerza — APPROVED** [review]

**Pull request merged**
