### PR TITLE
Add serial number of connected board to board details command

### PR DESCRIPTION
**Pull request by silvanocerza**
**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

Enhances an existing command with more information.

- **What is the current behavior?**

`board details <fqbn>` doesn't return the serial number of a connected board with the specified fqbn.

* **What is the new behavior?**

Calling `board details <fqbn>` when a board with that fqbn is connected that board serial number is returned in the json output and in the gRPC interface function.

- **Does this PR introduce a breaking change, and is
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

Nope.

* **Other information**:

None.

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
This is specific to the port, not to the board definition. Boards with the same FQBN can have different SN. So this information should be accessed via `arduino-cli board list --format json` not `board details`.

**Comment by silvanocerza** [comment]
@per1234 updated, should be good now.

**Review by ubidefeo — APPROVED** [review]
LGTM

**Comment by silvanocerza** [comment]
Force pushed to fix conflicts.

**Pull request merged**
