### PR TITLE
[breaking] Fix export binaries binding not working in gRPC interface

### PR DESCRIPTION
**Pull request by silvanocerza**
**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

This fixes a export binaries confing binding not working in the gRPC interface.

- **What is the current behavior?**

If a gRPC interface consumer sets `sketch.always_export_binaries` to `true` in its config file and sends a compilation request that that setting is ignored and binaries are not exported.

* **What is the new behavior?**

gRPC interface consumer can now set `sketch.always_export_binaries` to `true` in their config file and sends a compilation request to correctly export binaries.

- **Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

Yes, this PR contains a breaking change for gRPC consumers, the CLI is unaffected.

The gRPC interface `CompileReq` message had its `ExportBinaries` property type changed from `bool` to `google.protobuf.BoolValue`.

* **Other information**:

Solves #1103.

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

### CODE REVIEW

**Comment by kittaakos** [comment]
The CLI correctly picks up `sketch.always_export_binaries` from the CLI config so that part is OK. Unfortunately, it breaks `Export compiled Binaries`. I cannot force to export the binary if `sketch.always_export_binaries` is `false` in the config.

**Comment by silvanocerza** [comment]
That's unfortunate, I'll take a look at it.

**Comment by kittaakos** [comment]
Now I am puzzled. Let me do a couple of additional experiments, as it works now. It wasn't before.

**Comment by kittaakos** [comment]
> Let me do a couple of additional experiments, as it works now. It wasn't before.

I can confirm, it works as expected. There was a build issue on my side. Thank you for the fix, @silvanocerza 👍, and sorry for the confusion.

**Comment by silvanocerza** [comment]
Rebased to include integration tests fixes from #1183

**Review by cmaglie — APPROVED** [review]

**Pull request merged**
