### PR TITLE
Use $HOME environment for user's home directory first

### PR DESCRIPTION
**Pull request by phd**
Use $HOME environment variable for user's home directory first.
Only then fallback to os/user (parsing /etc/passwd).

This allows user to use a different directory by exporting own value for the $HOME variable.

### CODE REVIEW

**Comment by ultr** [comment]
bump

**Comment by masci** [comment]
Hi @phd and thanks for the contribution!

We recently switched to go 1.12 and we can use https://golang.org/pkg/os/#UserHomeDir now, can you change your patch so we can get the home path in a cross platform fashion?

**Comment by phd** [comment]
Hello @masci 
If I have access to my PC anytime soon, I will modify this patch and resubmit it.

**Comment by phd** [comment]
I have created a new pull request with the updated patch:
https://github.com/arduino/arduino-cli/pull/239

Unfortunately this one chance makes arduino-cli compilation fail on Go 1.10.
And sadly Go 1.12 is not widely adopted yet, ex. Ubuntu has Go 1.10 available by default in 18.04, 18.10 and latest 19.04 releases: https://packages.ubuntu.com/search?keywords=golang&searchon=names&exact=1&suite=all&section=all (yes, you can easily install Go 1.12, still it's not very convenient)

**Comment by masci** [comment]
Superseded by #239

**Pull request closed without merging**
