### PR TITLE
Allow port, protocol and port settings to be specified in profiles.

### LINKED ISSUE #2554: Allow storing the `protocol`+`port` info per sketch profile
### Describe the request

Please let the sketch profile file store the preferred `port` (address) and (port) `protocol` per profile.

Assuming [this](https://arduino.github.io/arduino-cli/latest/sketch-project-file/#build-profiles) format:

```yaml
profiles:
  <PROFILE_NAME>:
    notes: <USER_NOTES>
    fqbn: <FQBN>
    platforms:
      - platform: <PLATFORM> (<PLATFORM_VERSION>)
        platform_index_url: <3RD_PARTY_PLATFORM_URL>
      - platform: <PLATFORM_DEPENDENCY> (<PLATFORM_DEPENDENCY_VERSION>)
        platform_index_url: <3RD_PARTY_PLATFORM_DEPENDENCY_URL>
    libraries:
      - <LIB_NAME> (<LIB_VERSION>)
      - <LIB_NAME> (<LIB_VERSION>)
      - <LIB_NAME> (<LIB_VERSION>)

  ...more profiles here...
```

Please support this:
```diff
4a5,6
>     protocol: <PROTOCOL> # serial, network, teensy, etc.
>     port: <PORT> # /dev/ttyACM0, COM2, etc.
```

Thank you!

### Describe the current behavior

Currently, it's possible to store a single preferred `protocol`+`port` pair in the sketch profile.

```yaml
default_port: /dev/ttyACM0
default_protocol: serial
```

It would be great to store it per profile. If a profile does not specify a `port`/`protocol`, the `default_port`/`default_protocol` is used.

### Arduino CLI version

af0b60e6069d3c26b764f17dbbf83b269a9ddbf8

### Operating system

macOS

### Operating system version

11.7.10

#### Related

- https://github.com/arduino/arduino-ide/issues/1892 / https://github.com/arduino/arduino-ide/issues/2438
- https://github.com/arduino/arduino-ide/issues/136

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

### LINKED ISSUE #2640: feat: Allow --config strings in sketch.yaml (esp. baudrate)
### Describe the request

It would be nice if `sketch.yaml` let one specify the default `baudrate` for `arduino-cli monitor`, as 9600 baud is v...e...r...y...s...l...o...w... and typing `-c baudrate=115200` gets old. Obviously I can make a script wrapper or alias or something but I feel like this kind of thing is what profiles are all about.

(Per https://github.com/arduino/arduino-cli/issues/2554 this should probably be per-profile, not sketch-global.)

### Describe the current behavior

There's no (obvious) way to specify serial monitor baud rate (or other communications port properties) except on the command line.

### Arduino CLI version

1.0.0

### Operating system

Linux, N/A

### Operating system version

(true in all OS)

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

### PR DESCRIPTION
**Pull request by cmaglie**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [X] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

## What kind of change does this PR introduce?

* Allow specifying the default `port` and `protocol` on a per-profile basis.
* Allows specifying default port settings (like `baudrate`, etc...) on a per-sketch and per-profile basis.

## What is the current behavior?

Default port and protocol can not be specified per-profile.
Port settings can not be specified either per-sketch or per-profile.

## What is the new behavior?

The above features are now allowed inside `sketch.yaml`:

```
profiles:
  uno:
    fqbn: arduino:avr:uno
    platforms:
      - platform: arduino:avr (1.8.6)
    libraries:
      - RTClib (2.1.4)
      - Adafruit BusIO (1.16.1)
    port: /dev/ttyACM2
    port_config:
      baudrate: 9600
      bits: 9

default_fqbn: arduino:samd:arduino_zero_native
default_port: /dev/ttyACM0
default_port_config:
  baudrate: 115200
  bits: 9
```

## Other information

Fix #2640 
FIx #2554

### CODE REVIEW

**Review by alessio-perugini — COMMENTED** [review]
LGTM.

It would be awesome to add a test similar to [monitor_test.go](https://github.com/arduino/arduino-cli/blob/master/internal/integrationtest/monitor/monitor_test.go)
That tests for the new profile configs.

Do you think it can be done without too much pain?

**Comment by cmaglie** [comment]
> Do you think it can be done without too much pain?

Thanks to the new tests, I discovered a lot of weird subcases and some old tests that were **wrong**. :+1:

**Review by alessio-perugini — APPROVED** [review]
Awesome work with the tests. I've done a quick test on my Linux machine too and it works as expected.

:rocket:

**Comment by dankeboy36** [comment]
Hello, I originally suggested adding the protocol field in #2554 so IDEs or gRPC clients could restore a full port context (`address` + `protocol`) without rediscovery. The gRPC API mandates the `protocol` property, but it seems it’s never used in CLI execution. Only `--port` (address) matters, and the CLI's discovery infers the protocol. I kind of regret requesting this field now. Can we assume it defaults to serial if omitted? Maybe this is missing from the [sketch project file docs](https://arduino.github.io/arduino-cli/latest/sketch-project-file/#default-flags-for-arduino-cli-usage). I am happy to provide a patch. What do you think? Thank you

**Pull request merged**
