### PR TITLE
[skip ci] Added APT repo installation guidelines

### PR DESCRIPTION
**Pull request by Stig124**
**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

Docs update for my selfhosted apt repo for debian-based OS (#1111)
- **What is the current behavior?**

There is no "native" way to grab Arduino-CLI actually on Linux
* **What is the new behavior?**

I made a 24/7 available repo, using [reprepro](https://manpages.debian.org/buster/reprepro/reprepro.1.en.html) and nginx hosted on a OVH VPS, with all arch accessible except for `arm32` which would arrive soon
- **Does this PR introduce a breaking change, and is
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

No it's not
* **Other information**:

The repo is SSL-enabled on a secure TLD (so only HTTPS is allowed) and cloudflare proxied, packages are signed with a purpose-gen GPG subkey.

I'm the only person to have access to the server, and the GPG key passphrase is kept in cold storage when not needed

The script that generates the deb packages is open-source, uses only official builds, and available [here](https://github.com/Stig124/arduino-clidebfetchbuild)

Hit me up with any question/request as needed

Stig124
---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

### CODE REVIEW

**Comment by Stig124** [comment]
Oh, I failed to something here, I'll check that tomorrow

**Comment by ubidefeo** [comment]
no hurry @Stig124 

this has to go through some folks who will be on holiday for one more week ;)

**Comment by Stig124** [comment]
And that seems to be fixed

**Comment by tijuca** [comment]
It's of course legitimate to provide a own archive, but I personally would rather like to see that arduino-cli could be made available within Debian. Doing this all downstream distribution could take the advantages by pulling the binary and source packages into their distributions. We simply lacking people who want and can take care of this. By now the usage of another language (Go) for building binaries it's even more complicated.

**Comment by Stig124** [comment]
> It's of course legitimate to provide a own archive, but I personally would rather like to see that arduino-cli could be made available within Debian. Doing this all downstream distribution could take the advantages by pulling the binary and source packages into their distributions. We simply lacking people who want and can take care of this.

There is always OpenSUSE Build Service, to build for all distros at once, available for that, but the thing is that the executable is distro-agnostic, so creating a RPM-based repo is ultra simple, same as pushing to the AUR... all of that w/o any rebuilding and only needing repackaging

I am able to run a RPM-based repo (mainly for Fedora) if needed and can dig the docs to make a `PKGBUILD` to push to AUR

**Comment by Stig124** [comment]
I'm pulling out the PR, I need the server for other things

**Pull request closed without merging**
