### PR TITLE
Improved `{build.*.platform.path}` vars enumeration.

### PR DESCRIPTION
**Pull request by cmaglie**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [X] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

## What kind of change does this PR introduce?

This is a tentative fix for #2616. The original issue provided an experimental platform that extends `esp32` to experiment with.
This PR adds the following template variables that will be available to compose recipes:
* `{build.core.platform.path}` contains the path to the reference (build) platform
* `{build.board.platform.path}` contains the path to the board platform

Also, adds the input variable `build.use_core_platform_for_runtime_platform_path` to be set on `boards.txt` or `platform.txt`:
* if set to `true` then the value of `{runtime.platform.path}` will be the path to the reference platform.
* in all other cases (unset or `!=true`) the value of `{runtime.platform.path}` will be the path to the board platform (as it always has been)

## What is the current behavior?

The compile fails with an "extended" platforms

## What is the new behavior?

Unfortunately, the compile still fails. Hopefully, this PR could help to resolve the remaining issues.

## Other information

/cc @egnor

### CODE REVIEW

**Comment by egnor** [comment]
(kibitz: `build.use_core_platform_for_runtime_platform_path` might not be quite right, since it doesn't just affect the build but in fact just about any variable, including upload and so on?)

**Comment by egnor** [comment]
(This seems to work, by the way! -- see https://github.com/arduino/arduino-cli/issues/2616#issuecomment-2192746629 -- is it likely to land any time soon?)

**Comment by cmaglie** [comment]
> (kibitz: `build.use_core_platform_for_runtime_platform_path` might not be quite right, since it doesn't just affect the build but in fact just about any variable, including upload and so on?)

Uhm... ok I'll rename it to `runtime.use_core_platform_path_for_runtime_platform_path`.

> (This seems to work, by the way! -- see [#2616 (comment)](https://github.com/arduino/arduino-cli/issues/2616#issuecomment-2192746629) -- is it likely to land any time soon?)

Yes, sorry for the long delay, I'm updating the docs right now, and it should be ready for the next release.

**Review by alessio-perugini — APPROVED** [review]
lgtm

**Pull request merged**
