### PR TITLE
Add gRPC interface function to write settings to file

### PR DESCRIPTION
**Pull request by silvanocerza**
**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

Adds a new function to the gRPC interface.

- **What is the current behavior?**

There is currently no way to update the config file from the gRPC interface.

* **What is the new behavior?**

Consumers of the gRPC interface can now call a function `Write(*rpc.WriteRequest)` to write settings currently stored in memory to the file specified in `rpc.WriteRequest`.

- **Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

Nope.

* **Other information**:

None.

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
How about a demo in the client_example?
```diff
diff --git a/client_example/main.go b/client_example/main.go
index 4a6164b7..08cf1c43 100644
--- a/client_example/main.go
+++ b/client_example/main.go
@@ -90,6 +90,10 @@ func main() {
        log.Println("calling GetValue(foo)")
        callGetValue(settingsClient)

+       // Write settings to file.
+       log.Println("calling Write()")
+       callWrite(settingsClient)
+
        // Before we can do anything with the CLI, an "instance" must be created.
        // We keep a reference to the created instance because we will need it to
        // run subsequent commands.
@@ -256,6 +260,17 @@ func callGetAll(client settings.SettingsClient) {
        log.Printf("Settings: %s", getAllResp.GetJsonData())
 }

+func callWrite(client settings.SettingsClient) {
+       _, err := client.Write(context.Background(),
+               &settings.WriteRequest{
+                       FilePath: path.Join(dataDir, "written-settings.yml"),
+               })
+
+       if err != nil {
+               log.Fatalf("Error writing settings: %s", err)
+       }
+}
+
 func initInstance(client rpc.ArduinoCoreClient) *rpc.Instance {
        // The configuration for this example client only contains the path to
        // the data folder.
```

**Comment by silvanocerza** [comment]
> How about a demo in the client_example?

Yeah, that's a good idea. Sooner than later I want to ditch that `client_example` for a set of structured integration tests though.

Soon. :cry:

**Comment by per1234** [comment]
> I want to ditch that client_example for a set of structured integration tests though

I'm all for adding integration tests, but the purpose of `client_example` is documentation. I found it to be extremely helpful when I was documenting the gRPC interface. I don't think integration tests could serve as well as documentation. So I would like to see the client_example remain even after the tests are added.

**Comment by silvanocerza** [comment]
> > I want to ditch that client_example for a set of structured integration tests though
> 
> I'm all for adding integration tests, but the purpose of `client_example` is documentation. I found it to be extremely helpful when I was documenting the gRPC interface. I don't think integration tests could serve as well as documentation. So I would like to see the client_example remain even after the tests are added.

Ideally well written tests can act as documentation but I get your concerns.

**Review by per1234 — APPROVED** [review]

**Pull request merged**
