### PR TITLE
Fixed some error messages/warnings during index download

### LINKED ISSUE #2254: CLI cannot gracefully handle invalid 3rd party URLs when initializing the index
### Describe the problem

I am working on https://github.com/arduino/arduino-ide/issues/2021 after https://github.com/arduino/arduino-cli/pull/2119. I experience error messages when I initialize the `directories.data` folder via `core update-index`, and an invalid 3rd party URL is defined. The same problem is present via the gRPC API.

### To reproduce

I have a bleeding edge CLI from 1a85d168. Probably, the issue can be reproduced from https://github.com/arduino/arduino-cli/commit/62bb4c47cb2bb64f642cba050a958f45902202ee.

```sh
./arduino-cli version                         
arduino-cli  Version: git-snapshot Commit: 1a85d168 Date: 2023-08-02T10:28:17Z
```

This is my CLI `directories` and `additional_urls` config:

```sh
cat ~/.arduinoIDE/arduino-cli.yaml | yq .directories
```
```yaml
{
  "builtin": {
    "libraries": "/Users/a.kitta/Library/Arduino15/libraries"
  },
  "data": "/Users/a.kitta/Library/Arduino15",
  "downloads": "/Users/a.kitta/Library/Arduino15/staging",
  "user": "/Users/a.kitta/Documents/Arduino"
}
```

```sh
cat ~/.arduinoIDE/arduino-cli.yaml | yq .board_manager.additional_urls
```
```yaml
[
  "https://invalidUrl"
]
```

My `directories.data` location is "empty":

```sh
ls ~/Library/Arduino15
inventory.yaml
```

:x: Update the indexes using the CLI config. It fails:

```sh
./arduino-cli core update-index --config-file ~/.arduinoIDE/arduino-cli.yaml --format json
```
```json
{
  "error": "Some indexes could not be updated.",
  "warnings": [
    "Error initializing instance: Loading index file: loading json index file /Users/a.kitta/Library/Arduino15: read /Users/a.kitta/Library/Arduino15: is a directory"
  ]
}
```

:x: Try to run a platform search. It also fails:

```sh
./arduino-cli core search "arduino:avr"  --config-file ~/.arduinoIDE/arduino-cli.yaml --format json
```
```json
{
  "error": "Some indexes could not be updated.",
  "warnings": [
    "Error initializing instance: Loading index file: loading json index file /Users/a.kitta/Library/Arduino15: read /Users/a.kitta/Library/Arduino15: is a directory"
  ]
}
```

### Expected behavior

The CLI can gracefully handle when a 3rd party package URL is invalid during the index update.
The CLI reports if the URL is invalid. This is working as expected in IDE `2.1.1` with CLI `0.33.1`.

Screenshot 2023-08-02 at 14 00 35

If I use the default `text` output, I see the expected `no such host` error. But it's missing from the JSON and gRPC levels.

```
./arduino-cli core search "arduino:avr"  --config-file ~/.arduinoIDE/arduino-cli.yaml             
Downloading index: package_index.tar.bz2 downloaded                                             
Downloading index: . Get "https://invalidUrl": dial tcp: lookup invalidUrl: no such host
Error initializing instance: Loading index file: loading json index file /Users/a.kitta/Library/Arduino15: read /Users/a.kitta/Library/Arduino15: is a directory
Downloading index: package_index.tar.bz2 downloaded                                             
Downloading index: . Get "https://invalidUrl": dial tcp: lookup invalidUrl: no such host
Some indexes could not be updated.
```

### Arduino CLI version

62bb4c47cb2bb64f642cba050a958f45902202ee

### Operating system

macOS

### Operating system version

13.4.1

### Additional context

I have noticed that although there is an error message, the primary package and the libraries index files are there, and the tools exist.

```
rm -rf ~/Library/Arduino15
```

```
./arduino-cli core update-index --config-file ~/.arduinoIDE/arduino-cli.yaml --format json
{
  "error": "Some indexes could not be updated.",
  "warnings": [
    "Error initializing instance: Loading index file: loading json index file /Users/a.kitta/Library/Arduino15: read /Users/a.kitta/Library/Arduino15: is a directory"
  ]
}
```

```
tree ~/Library/Arduino15
/Users/a.kitta/Library/Arduino15
├── inventory.yaml
├── library_index.json
├── library_index.json.sig
├── package_index.json
├── package_index.json.sig
├── packages
│   └── builtin
│       └── tools
│           ├── ctags
│           │   └── 5.8-arduino11
│           │       └── ctags
│           ├── dfu-discovery
│           │   └── 0.1.2
│           │       ├── LICENSE.txt
│           │       └── dfu-discovery
│           ├── mdns-discovery
│           │   └── 1.0.9
│           │       ├── LICENSE.txt
│           │       └── mdns-discovery
│           ├── serial-discovery
│           │   └── 1.4.0
│           │       ├── LICENSE.txt
│           │       └── serial-discovery
│           └── serial-monitor
│               └── 0.13.0
│                   ├── LICENSE.txt
│                   └── serial-monitor
├── staging
│   └── packages
│       ├── ctags-5.8-arduino11-pm-x86_64-apple-darwin.zip
│       ├── dfu-discovery_v0.1.2_macOS_64bit.tar.gz
│       ├── mdns-discovery_v1.0.9_macOS_64bit.tar.gz
│       ├── serial-discovery_v1.4.0_macOS_64bit.tar.gz
│       └── serial-monitor_v0.13.0_macOS_64bit.tar.gz
└── tmp

16 directories, 19 files
```

I have also noticed that executing any subsequent `core search` commands produce the same error message, while `core list` does not.

```
./arduino-cli core search "" --config-file ~/.arduinoIDE/arduino-cli.yaml --format json
{
  "error": "Some indexes could not be updated.",
  "warnings": [
    "Error initializing instance: Loading index file: loading json index file /Users/a.kitta/Library/Arduino15: read /Users/a.kitta/Library/Arduino15: is a directory"
  ]
}
```
```
./arduino-cli core list --config-file ~/.arduinoIDE/arduino-cli.yaml --format json
[]
```

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by cmaglie**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [X] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

## What kind of change does this PR introduce?

Some error messages are adjusted to better represent the actual error.
1. During index download if the server is not available.
2. During index loading if the URL is wrong.

## What is the current behavior?

Following the steps in #2254 I get:

```
$ arduino-cli core update-index --format json
{
  "error": "Some indexes could not be updated.",
  "warnings": [
    "Error initializing instance: Loading index file: loading json index file /home/megabug/.arduino15: read /home/megabug/.arduino15: is a directory"
  ]
}
```

## What is the new behavior?

```
$ arduino-cli core update-index --format json
{
  "error": "Some indexes could not be updated.",
  "warnings": [
    "Error initializing instance: Error downloading index 'https://invalidurl': Invalid URL",
    "Error initializing instance: Loading index file: Invalid URL: https://invalidurl"
  ]
}
```

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

No

## Other information

Fix #2254

### CODE REVIEW

**Review by kittaakos — APPROVED** [review]
✅ I get the error message if the invalid 3rd party URL is `https://invalidUrl`. Thank you! 👍 

```sh
% ./arduino-cli version
arduino-cli  Version: git-snapshot Commit: b39c45b9 Date: 2023-08-02T17:26:45Z
% cat ~/.arduinoIDE/arduino-cli.yaml | yq .directories
{
  "builtin": {
    "libraries": "/Users/a.kitta/Library/Arduino15/libraries"
  },
  "data": "/Users/a.kitta/Library/Arduino15",
  "downloads": "/Users/a.kitta/Library/Arduino15/staging",
  "user": "/Users/a.kitta/Documents/Arduino"
}
% cat ~/.arduinoIDE/arduino-cli.yaml | yq .board_manager.additional_urls
[
  "https://invalidUrl"
]
% ls ~/Library/Arduino15
inventory.yaml
% ./arduino-cli core update-index --config-file ~/.arduinoIDE/arduino-cli.yaml --format json
{
  "error": "Some indexes could not be updated.",
  "warnings": [
    "Error initializing instance: Some indexes could not be updated.",
    "Error initializing instance: Loading index file: Invalid URL: https://invalidUrl"
  ]
}
```

**Comment by kittaakos** [comment]
During the review, I noticed something with the URL parsing. Is this a bug?

When I changed the 3rd party URL to `https://http://file://notafile`, I would have expected a different error message. Something like an invalid URL, but I got:

```
"Error initializing instance: Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/notafile: open /Users/a.kitta/Library/Arduino15/notafile: no such file or directory"
```

```sh
% cat ~/.arduinoIDE/arduino-cli.yaml | yq .board_manager.additional_urls
[
  "https://http://file://notafile"
]
% ./arduino-cli core update-index --config-file ~/.arduinoIDE/arduino-cli.yaml --format json
{
  "error": "Some indexes could not be updated.",
  "warnings": [
    "Error initializing instance: Some indexes could not be updated.",
    "Error initializing instance: Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/notafile: open /Users/a.kitta/Library/Arduino15/notafile: no such file or directory"
  ]
}
```

I thought it was because the last URL scheme was picked up; it was `file`, and the CLI tried to load a file. I changed the URL to `https://http://ssfile://notafile`, then I got the same error: `Error initializing instance: Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/notafile: open /Users/a.kitta/Library/Arduino15/notafile: no such file or directory`. Changing the URL to `https://http://ssfile://notafile` or `https://http://ssfilex://notafile` produced the same error message. How does the URL parsing work? If I write `file` anywhere in the URL, does the CLI try to locate a file in the data folder? Thanks!

**Comment by cmaglie** [comment]
> When I changed the 3rd party URL to `https://http://file://notafile`, I would have expected a different error message. Something like an invalid URL, but I got:

`https://http://file://notafile` it's a bit convoluted but it's still a valid URL, it breaks down as:

Scheme: `https`
Host: `http:` (hostname `http` with implicit port)
Path: `//file://notafile` (equivalent to `/file:/notafile` you can actually use // as a single / anywhere in a path...)

https://go.dev/play/p/barpaG3S9Q0

so basically the CLI is trying to download `notafile` as an index, and also it tries to load a (possibly) already downloaded index called `notafile`.

Maybe we should enforce the `.json` extension or at least the `package_[*_]index.*` name format?

**Review by alessio-perugini — APPROVED** [review]

**Comment by cmaglie** [comment]
> Maybe we should enforce the .json extension or at least the package_[*_]index.* name format?

while we decide this, I'll move forward this one.

**Pull request merged**
