### PR TITLE
[skip changelog] Notarize nightly macOS build

### PR DESCRIPTION
**Pull request by per1234**
**Please check if the PR fulfills these requirements**
- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls) before creating one)
- [x] The PR follows [our contributing guidelines](https://arduino.github.io/arduino-cli/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?**

Feature?

* **What is the current behavior?**

macOS nightly builds are not notarized.

* **What is the new behavior?**

macOS nightly builds are notarized.

* **Does this PR introduce a breaking change?**

No.

* **Other information**:

Nightly build from testing: https://downloads.arduino.cc/arduino-cli/nightly/arduino-cli_nightly_test-20200708_macOS_64bit.tar.gz

### CODE REVIEW

**Comment by kittaakos** [comment]
Is there a way to reuse the same job instead of copying it from the release to the nighty? I mean, once we have to change the workflow, we have to change it everywhere.

**Comment by per1234** [comment]
At least as far as the "Download Gon" and "Notarize binary, re-package it and update checksum" steps go, the "GitHub Actions way" would be to make an action (or use an existing action).

We could also host a script in a centralized location and then download/source that from each workflow.

**Comment by kittaakos** [comment]
> We could also host a script in a centralized

I would do that. Templates should be supported by GH Actions, just like it is supported in Azure.
I submitted a feature request and posted the same request [here](https://github.community/t/templates-for-github-actions/18045/3).

**Comment by kittaakos** [comment]
> Is there a way to reuse the same job instead of copying it from the release to the nighty?

Apparently, it's not possible out of the box. GH Actions does not support templates natively. Sorry for the noise here.

**Pull request merged**
