### PR TITLE
Fix time format RFC3339 in version #283

### LINKED ISSUE #283: Wrong Date format in version output
## Bug Report
The date output is not a RFC3339 format

### Current behavior

Build date does not have an easy parseable date format like RFC3339
now the CLI output is:
```
./arduino-cli version --format json | jq .build_date
"2019-07-16 15:06:29.7368222 +0000 UTC"
```

### Expected behavior

it was supposed to use: https://golang.org/pkg/time/#Time.Format
it should print something RFC3339 compatible, not a custom Go language format

### Environment

- CLI version (output of `arduino-cli version`):
{
  "command": "arduino-cli",
  "version": "0.3.7-alpha.preview",
  "commit": "",
  "build_date": "2019-07-16 15:09:59.2173451 +0000 UTC"
}
- Go version (if building from sources):
1.12.5
- OS version:
Windows and Linux

### Additional context
This was needed to improve command line testing.

### PR DESCRIPTION
**Pull request by u5surf**
Fixes #283 
I added `time.Format(time.RFC3339)` in version

### CODE REVIEW

**Comment by masci** [comment]
@u5surf thanks for the PR, my apologies but you got caught right in the middle of an invasive merge, can you rebase on master and solve the conflicts? :bowing_man:

**Comment by mastrolinux** [comment]
The PR now perfectly fixes the standard output format, it does not solve yet the --format json case.
```
$ ./arduino-cli version 
arduino-cli Version: 0.3.7-alpha.preview Commit:  BuildDate: 2019-07-17T15:24:18Z
$ ./arduino-cli version --format json
{
  "Application": "arduino-cli",
  "VersionString": "0.3.7-alpha.preview",
  "Commit": "",
  "BuildDate": "2019-07-17T15:27:41.7405288Z"
```

Do you like to update the PR to completely fix #283 ?
Thanks for your help @u5surf !

**Comment by masci** [comment]
We could add a `ToJSON()` method to the `VersionInfo` struct so we keep the format definition in one place

**Comment by u5surf** [comment]
@mastrolinux I updated the PR to fix the both of format.
@masci Thx reviewing. After all, I implemented the new type rfc3339Time which has the string formatter and JsonMarshal function.

**Pull request merged**
