### PR TITLE
feat: specialize init errors

### LINKED ISSUE #1762: As a gRPC consumer of the CLI, I need better error codes to distinguish between errors
### Describe the request

To keep the startup performance OK, the [IDE2](https://github.com/arduino/arduino-ide) does not run a core and library index update before initializing the gRPC client. The Arduino core client initialization in the IDE2 happens the following way:
 - create the gRPC core client,
 - init the core client,
 - run the index update asynchronously.

However, this does not always work. The command line CLI auto-magically updates the core and lib indexes on the first run (https://github.com/arduino/arduino-cli/pull/1043). This is not available when consuming the CLI's capabilities via the gRPC APIs.

On the first start (`directories/data` is missing or empty), the gRPC init step will fail with the following errors:
```json
[
  { "code": 9, "message": "Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/package_index.json: open /Users/a.kitta/Library/Arduino15/package_index.json: no such file or directory" },
  { "code": 9, "message": "Error loading hardware platform: discovery builtin:serial-discovery not found" },
  { "code": 9, "message": "Error loading hardware platform: discovery builtin:mdns-discovery not found" },
  { "code": 9, "message": "Loading index file: reading library_index.json: open /Users/a.kitta/Library/Arduino15/library_index.json: no such file or directory" }
]
```
When the IDE2 sees these errors, IDE2 knows that this is the first start, and the core and lib indexes must be updated before running the init phase of the gRCP core client. The above error is recoverable in IDE2.

----

There are "ignorable" errors. For example, if I use the `https://arduino.esp8266.com/stable/package_esp8266com_index.json` 3rd party URL, and install the `3.0.0` version (see the steps [here](https://github.com/arduino/arduino-ide/issues/1036#issuecomment-1152449530)), then there will be an [error](https://github.com/arduino/arduino-cli/blob/76fab32d9b758ecc38a29f7c75be805ea412f9ea/rpc/cc/arduino/cli/commands/v1/commands.proto#L216) status:
```json
{ "code": 9, "message": "Error loading hardware platform: loading platform release esp8266:esp8266@3.0.0: loading boards: skipping loading of boards esp8266:esp8266:espduino: malformed custom board options" }
```
This error does not cause any CLI error, so should be ignored.

### Describe the current behavior

All errors the IDE2 receives from the CLI have `code: 9`. There is no way to detect if the error is recoverable, non-recoverable, or ignorable.

It would be great if some details about the error would be available.

### Arduino CLI version

0.23.0

### Operating system

macOS

### Operating system version

12.3.1

### Additional context

Related: https://github.com/arduino/arduino-cli/pull/1251

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

### PR DESCRIPTION
**Pull request by Bikappa**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

## What kind of change does this PR introduce?

Makes some errors easier to recognize, with no text parsing, on the client side.

## What is the current behavior?

Most of the errors follow the standard [grpc error model](https://grpc.io/docs/guides/error/#standard-error-model) which is limited around the structure of data it carries. 

## What is the new behavior?

More errors in the instance initialization logic now have a richer standard that allows them to be easily machine-recognizable on the client side

## Other information

Fixes #1762 (at least in its original demand, a following initiative should be pursued to make all errors following a richer standard)

### CODE REVIEW

**Review by cmaglie — APPROVED** [review]
👍🏼

**Comment by kittaakos** [comment]
Hi, thanks for moving the request forward. IDE2 is eager to try it out. I do not understand something. Can you please help?

There is no error when the library index is missing. I am unfamiliar with the go code, but maybe [here](https://github.com/arduino/arduino-cli/blob/d48eb6e248cceabedd28bd2cbd141660c836c5d2/commands/instances.go#L406). When I wipe my `directories.data` location and `Create` and `Init` a client. I get this error:

```bash
rpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Create
```

```json
{
  "instance": {
    "id": 1
  }
}
```

```bash
grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Init
```

```json
{
  "error": {
    "code": 9,
    "message": "Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/package_index.json: open /Users/a.kitta/Library/Arduino15/package_index.json: no such file or directory",
    "details": [
      {"@type":"type.googleapis.com/cc.arduino.cli.commands.v1.FailedInstanceInitError","message":"Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/package_index.json: open /Users/a.kitta/Library/Arduino15/package_index.json: no such file or directory","reason":"FAILED_INSTANCE_INIT_REASON_INDEX_LOAD_ERROR"}
    ]
  }
}
{
  "error": {
    "code": 9,
    "message": "Error loading hardware platform: discovery builtin:serial-discovery not found",
    "details": [
      {"@type":"type.googleapis.com/cc.arduino.cli.commands.v1.PlatformLoadingError"}
    ]
  }
}
{
  "error": {
    "code": 9,
    "message": "Error loading hardware platform: discovery builtin:mdns-discovery not found",
    "details": [
      {"@type":"type.googleapis.com/cc.arduino.cli.commands.v1.PlatformLoadingError"}
    ]
  }
}
{
  "error": {
    "code": 9,
    "message": "Loading index file: reading library_index.json: open /Users/a.kitta/Library/Arduino15/library_index.json: no such file or directory"
  }
}
```

👆 Notice the missing `details[]` when the `library_index.json` file is missing.

Why does the CLI distinguish between `FailedInstanceInitError` and `PlatformLoadingError`? From the caller's point of view, it's still impossible to decide if the primary package index loading has failed, so the CLI/IDE2 is not functional, or loading a 3rd part platform has failed, which does not break the CLI/IDE2 functionality.

```json
{
    "code": 9,
    "message": "Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/package_index.json: open /Users/a.kitta/Library/Arduino15/package_index.json: no such file or directory",
    "detailsList": [
        {
            "typeUrl": "type.googleapis.com/cc.arduino.cli.commands.v1.FailedInstanceInitError",
            "value": "CAIStAFMb2FkaW5nIGluZGV4IGZpbGU6IGxvYWRpbmcganNvbiBpbmRleCBmaWxlIC9Vc2Vycy9hLmtpdHRhL0xpYnJhcnkvQXJkdWlubzE1L3BhY2thZ2VfaW5kZXguanNvbjogb3BlbiAvVXNlcnMvYS5raXR0YS9MaWJyYXJ5L0FyZHVpbm8xNS9wYWNrYWdlX2luZGV4Lmpzb246IG5vIHN1Y2ggZmlsZSBvciBkaXJlY3Rvcnk="
        }
    ]
}
```

```json
{
    "code": 9,
    "message": "Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/package_teensy_index.json: open /Users/a.kitta/Library/Arduino15/package_teensy_index.json: no such file or directory",
    "detailsList": [
        {
            "typeUrl": "type.googleapis.com/cc.arduino.cli.commands.v1.FailedInstanceInitError",
            "value": "CAISwgFMb2FkaW5nIGluZGV4IGZpbGU6IGxvYWRpbmcganNvbiBpbmRleCBmaWxlIC9Vc2Vycy9hLmtpdHRhL0xpYnJhcnkvQXJkdWlubzE1L3BhY2thZ2VfdGVlbnN5X2luZGV4Lmpzb246IG9wZW4gL1VzZXJzL2Eua2l0dGEvTGlicmFyeS9BcmR1aW5vMTUvcGFja2FnZV90ZWVuc3lfaW5kZXguanNvbjogbm8gc3VjaCBmaWxlIG9yIGRpcmVjdG9yeQ=="
        }
    ]
}
```

Can CLI have a more expressive name for the `PlatformLoadingError`;  maybe hardware platform or (discovery) tool loading error? I think `PlatformLoadingError` is misleading for consumers.

**Comment by kittaakos** [comment]
When does the CLI provide the `FAILED_INSTANCE_INIT_REASON_TOOL_LOAD_ERROR` reason? I deleted the `directories.data` folder, but I get the following error:

```json
{
  "error": {
    "code": 9,
    "message": "Error loading hardware platform: discovery builtin:serial-discovery not found",
    "details": [
      {"@type":"type.googleapis.com/cc.arduino.cli.commands.v1.PlatformLoadingError"}
    ]
  }
}
```
I would expect something like this:

```json
{
  "error": {
    "code": 9,
    "message": "Error loading hardware platform: discovery builtin:serial-discovery not found",
    "details": [
      {"@type":"type.googleapis.com/cc.arduino.cli.commands.v1.FailedInstanceInitError","message":"Error loading hardware platform: discovery builtin:serial-discovery not found","reason":"FAILED_INSTANCE_INIT_REASON_TOOL_LOAD_ERROR"}
    ]
  }
}
```

From the docs:

>   // FAILED_INSTANCE_INIT_REASON_TOOL_LOAD_ERROR failure encountered while
>  // loading a tool

**Comment by Bikappa** [comment]
Hi @kittaakos,
`PlatformLoadingError` was added in `details` to all the errors that were already classified of type `PlatformLoadingError` in the code, but were missing a machine readable/fixed field. Those are basically the ones starting with "Error loading hardware platform: in english.

`FailedInstanceInitError` was added in `details` to those errors which were not classified in code and returned as generic rpc statuses. The `reason` field of these has been arbitrary created from the pre-existing free form error messages. Please see below if you have suggestions on this field.
Note regarding:
> Notice the missing details[] when the library_index.json file is missing.

it was left behind in this category. I'm preparing a follow up pr for it.

If I understand correctly you are suggesting to wrap `PlatformLoadingError` into a `FailedInstanceInitError` and make it recognizable by `reason` instead of `type` in the detail element or perhaps dropping the "Platform" trait entirely like in

> {"@type":"type.googleapis.com/cc.arduino.cli.commands.v1.FailedInstanceInitError","message":"Error loading hardware platform: discovery builtin:serial-discovery not found","reason":"FAILED_INSTANCE_INIT_REASON_TOOL_LOAD_ERROR"}

I like the approach and I'm including it in the aforementioned follow-up pr. But if further differentiation is desired from the CLI output: like different types of `PlatformLoadingError`s  or the information about the severity of the error for the CLI functioning I'd strongly suggest to prepare rfc/document so to align on all scenarios where we want error details and which these should be. It would help prevent indefinite and long iterations on the subject.

**Pull request merged**
