### PR TITLE
Added Type field to Platform gRPC struct

### PR DESCRIPTION
**Pull request by cmaglie**
**Please check if the PR fulfills these requirements**

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [X] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**
Add `category` field to `Platform` gRPC struct

- **Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**
No

### CODE REVIEW

**Comment by cmaglie** [comment]
Related to https://github.com/arduino/arduino-ide/issues/177

**Comment by kittaakos** [comment]
This does not seem to be correct:

`./arduino-cli lib search "ArduinoOTA" --format json`:

Part of the output JSON:
```json
"latest": {
        "author": "Arduino,Juraj Andrassy",
        "version": "1.0.8",
        "maintainer": "Juraj Andrassy \u003cjuraj.andrassy@gmail.com\u003e",
        "sentence": "Upload sketch over network to Arduino board with WiFi or Ethernet libraries",
        "paragraph": "Based on WiFi101OTA library. Uploads over Ethernet, EthernetENC, WiFi101, WiFiNina, WiFiEspAT to SAMD, nRF5, RP2040, STM32F1, ESP and to classic ATmega with more than 64 kB flash memory.",
        "website": "https://github.com/jandrassy/ArduinoOTA",
        "category": "Other",
        "architectures": [
          "*"
        ],
        "types": [
          "Contributed"
        ],
        "resources": {
          "url": "https://downloads.arduino.cc/libraries/github.com/jandrassy/ArduinoOTA-1.0.8.zip",
          "archive_filename": "ArduinoOTA-1.0.8.zip",
          "checksum": "SHA-256:d36504623df593ea79db03ec6eb2601c45055ba0583414fced02b1c16ff7a779",
          "size": 82017,
          "cache_path": "libraries"
        },
        "provides_includes": [
          "ArduinoOTA.h"
        ]
      }
```

`types` (which is available only from `LibraryRelease`) should be an array of these values:
Screen Shot 2022-08-29 at 13 38 27


And the `category` should be one of these:
Screen Shot 2022-08-29 at 13 38 50


For the platforms, `type` is not present, and `category` is:
Screen Shot 2022-08-29 at 13 39 46


This is not working correctly; see JSON above.

**Comment by cmaglie** [comment]
@kittaakos 
I've renamed `category` field to `type` so the meaning matches on both platform and libraries. Also the type has been changed from `string` to `[]string`.

**Review by kittaakos — COMMENTED** [review]
I tried the functionality from https://github.com/arduino/arduino-ide/pull/1361. The `Type` and `Topic` filters work as in IDE (1.x).

Thank you for the support!

**Review by kittaakos — APPROVED** [review]

**Pull request merged**
