### PR TITLE
Added `--timestamp` option to monitor command.

### LINKED ISSUE #2316: Monitor: show timestamp when receiving messages
### Describe the request

When opening the serial monitor with `arduino-cli monitor -p /dev/ttyACM0` would be cool to prefix the timestamp of a message received from the serial.
We can add a new flag like `--show-timestamp` that enables such a feature.

Expected output:
```bash
[2023-09-13 16:55:22] Message from serial
[2023-09-13 16:55:25] another message
[2023-09-13 16:55:30] a
[2023-09-13 16:55:35] bcd
```

### Describe the current behavior

When we receive a message from the serial monitor we just show them without prefixing the timestamp.

### Arduino CLI version

-

### Operating system

Linux

### Operating system version

Ubuntu 23.04

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

### PR DESCRIPTION
**Pull request by zvonler**
## Please check if the PR fulfills these requirements

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## What kind of change does this PR introduce?

New feature in the monitor that can add a timestamp to the beginning of each received line.

## What is the current behavior?

No such option.

## What is the new behavior?

When `--timestamp` is provided, the monitor wraps the output tty with a timestamping Writer. The format of the timestamps is `YYYY-mm-dd HH:MM:SS`.

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

Negative.

## Other information

This is my first time writing Go (except for the sample program I used to work out the approach), so please review carefully.

There don't appear to be any docs specifically about the monitor command, nor tests of the CLI entry point.

The change was tested by hand using this sketch:
```
void setup()
{
    Serial.begin(115200);
}

static const uint32_t period = 100; // millis

void loop()
{
    static uint32_t last_print_tm = 0;
    static uint8_t next_ch = 0;
    static const char* message = "tick\n";
    if (millis() - last_print_tm > period) {
        Serial.print(message[next_ch++]);
        if (message[next_ch] == '\0')
            next_ch = 0;
        last_print_tm += period;
    }
    delay(10);
}
```

Testing confirmed that individual non-newline characters received are still output immediately, and only newline characters cause the timestamp output:
```
Zacharys-iMac:arduino-cli zvonler$ ./arduino-cli -b adafruit:avr:metro monitor -p /dev/cu.usbserial-015F62D6 -c baudrate=115200 --quiet
tick
tick
tick
tick
ti^C
Zacharys-iMac:arduino-cli zvonler$ ./arduino-cli -b adafruit:avr:metro monitor -p /dev/cu.usbserial-015F62D6 -c baudrate=115200 --quiet --timestamp
[2023-09-22 12:12:18] tick
[2023-09-22 12:12:19] tick
[2023-09-22 12:12:19] tick
[2023-09-22 12:12:20] tick
[2023-09-22 12:12:20] tic^C
Zacharys-iMac:arduino-cli zvonler$ 
```

### CODE REVIEW

**Comment by alessio-perugini** [comment]
:wave: Thank you, for the contribution. The implementation looks good. :star_struck: 
As you noticed, we do not have any integration tests for the monitor as we cannot provide a real board in the CI.
We can do a unit test in the same folder you're working on by creating a new `monitor_test.go` file. You can look at [this](https://github.com/arduino/arduino-cli/blob/master/arduino/monitor/monitor_test.go) for some inspiration. In this case, the package name doesn't need to have the suffix `_test` as we need to access a private function.

The idea is to test only the `timeStampWriter`. These are some hints:
- We call the `newTimeStampWriter` providing something that satisfies the `io.Writer` like (bytes.Buffer{})
- We "simulate" the data coming from the board by passing arbitrary input in the `timeStampWriter.Write` func
- Once done writing, we should be able to assert the content of the buffer if has the timestamp as a prefix. 

If you need help don't hesitate to ping me I'd be more than happy to guide you. :muscle:

**Comment by zvonler** [comment]
Thanks for the pointers, I'll add a test like you described.

**Comment by zvonler** [comment]
Test added and formatting fixed.

**Comment by zvonler** [comment]
Oops, fixed that last formatting issue.

**Comment by alessio-perugini** [comment]
I've done some manual testing, and it works flawlessly. Thank you for your contribution and your patience. :nerd_face: 

image

**Review by alessio-perugini — APPROVED** [review]

**Pull request merged**
