### PR TITLE
Libraries compatibility is now shown when calling lib list with fqbn

### LINKED ISSUE #955: Please review the exit code of the `lib list -b` command
## Bug Report

This is a minor thing, maybe not even an issue but the expected behavior. When I run `lib list -b` command without any libraries **and** any cores installed, I always get a `0` exit code. However, when I have at least one user library installed, but still no cores, I always get a non-zero, `1` exit code. This feels inconsistent.

### Current behavior

```
% rm -rf ~/Library/Arduino15 && rm -rf ~/Documents/Arduino/libraries
% ./arduino-cli version
arduino-cli Version: 0.13.0 Commit: 693a045
% ./arduino-cli core update-index
Downloading missing tool builtin:ctags@5.8-arduino11...
builtin:ctags@5.8-arduino11 downloaded                                                                                                                          
Installing builtin:ctags@5.8-arduino11...
builtin:ctags@5.8-arduino11 installed
Downloading missing tool builtin:serial-discovery@1.0.0...
builtin:serial-discovery@1.0.0 downloaded                                                                                                                       
Installing builtin:serial-discovery@1.0.0...
builtin:serial-discovery@1.0.0 installed
Updating index: library_index.json downloaded                                                                                                                   
Updating index: package_index.json downloaded                                                                                                                   
Updating index: package_index.json.sig downloaded                                                                                                               
Updating index: package_index.json downloaded                                                                                                                   
Updating index: package_index.json.sig downloaded                                                                                                               
% ./arduino-cli core list        
% ./arduino-cli lib list -b arduino:samd:mkr1000                    
No libraries installed.
% echo $?                                                           
0
% ./arduino-cli lib install "AllThingsTalk LoRaWAN SDK"             
AllThingsTalk LoRaWAN SDK depends on AllThingsTalk LoRaWAN SDK@3.1.6
Downloading AllThingsTalk LoRaWAN SDK@3.1.6...
AllThingsTalk LoRaWAN SDK@3.1.6 downloaded                                                                                                                      
Installing AllThingsTalk LoRaWAN SDK@3.1.6...
Installed AllThingsTalk LoRaWAN SDK@3.1.6
% ./arduino-cli lib list -b arduino:samd:mkr1000       
Error listing Libraries: loading board data: platform arduino:samd is not installed
% echo $?                                              
1
% 
```

### Expected behavior

I would expect to have `1` exit code with a similar error message (`platform x:y is not installed`) when no user libraries **and** no cores are installed.

### Environment

- CLI version (output of `arduino-cli version`): `arduino-cli Version: 0.13.0 Commit: 693a045`
- OS and platform: macOS Catalina (`10.15.6 (19G2021)`)

### Additional context

If this is the expected behavior, please close the issue with a remark. Thank you!

### PR DESCRIPTION
**Pull request by silvanocerza**
**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?**
Changes the behaviour of `lib list` command and related gRPC interface. 
The return codes of the command are also more consistent to fix #955.

- **What is the current behavior?**
Calling `lib list -b <fqbn>` returns the same output as `lib list`.

* **What is the new behavior?**
Calling `lib list -b <fqbn>` shows which libraries compatibility with the board specified by the `fqbn`.

Example output:
```
$ ./arduino-cli lib list                        
Name                      Installed Available    Location Description                                                    
AllThingsTalk_LoRaWAN_SDK 3.1.6     -            user     LoRaWAN SDK for AllThingsTalk Maker                            
ArduinoJson               6.16.1    -            user     A simple and efficient JSON library f...                       
wm8978-esp32              1.0.0     -            user     An esp32 library for the wm8978 dac.                           

$ ./arduino-cli lib list -b arduino:samd:mkr1000
Name                      Installed Available    Compatible   Location Description                                                    
AllThingsTalk_LoRaWAN_SDK 3.1.6     -            ✓            user     LoRaWAN SDK for AllThingsTalk Maker                            
ArduinoJson               6.16.1    -            ✓            user     A simple and efficient JSON library f...                       
wm8978-esp32              1.0.0     -            ✕            user     An esp32 library for the wm8978 dac.     
```

- **Does this PR introduce a breaking change?**
Nope.

* **Other information**:
None.

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

### CODE REVIEW

**Comment by ubidefeo** [comment]
@silvanocerza  can I see the JSON output?

**Comment by ubidefeo** [comment]
@silvanocerza 
so for not compatible libraries you don't have a `compatible` property in the JSON section at all?
I would prefer to see it and make it part of the standard response.
A user might want to scan through all the not compatible libraries and do something about it, such as reporting :)

**Comment by silvanocerza** [comment]
@ubidefeo I've noticed that but I assumed it was an expected behaviour of feedback library since other keys are missing too, I'll take a look at it.

**Comment by silvanocerza** [comment]
New output.

```
$ ./arduino-cli lib list               
Name         Installed Available    Location Description                                                      
ArduinoJson  6.16.1    -            user     A simple and efficient JSON library f...                         
wm8978-esp32 1.0.0     -            user     An esp32 library for the wm8978 dac.                             

$ ./arduino-cli lib list -b arduino:samd:mkr1000              
Name        Installed  Available         Location Description                                                        
ArduinoJson 6.16.1     -                 user     A simple and efficient JSON library f...                           
```


This is `lib list --format json`:

```[
  {
    "library": {
      "name": "ArduinoJson",
      "author": "Benoit Blanchon \u003cblog.benoitblanchon.fr\u003e",
      "maintainer": "Benoit Blanchon \u003cblog.benoitblanchon.fr\u003e",
      "sentence": "A simple and efficient JSON library for embedded C++.",
      "paragraph": "ArduinoJson supports ✔ serialization, ✔ deserialization, ✔ MessagePack, ✔ fixed allocation, ✔ zero-copy, ✔ streams, ✔ filtering, and more. It is the most popular Arduino library on GitHub ❤❤❤❤❤. Check out arduinojson.org for a comprehensive documentation.",
      "website": "https://arduinojson.org/?utm_source=meta\u0026utm_medium=library.properties",
      "category": "Data Processing",
      "architectures": [
        "*"
      ],
      "install_dir": "/home/alien/Arduino/libraries/ArduinoJson",
      "source_dir": "/home/alien/Arduino/libraries/ArduinoJson/src",
      "real_name": "ArduinoJson",
      "version": "6.16.1",
      "license": "MIT",
      "location": 1,
      "layout": 1,
      "examples": [
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonConfigFile",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonFilterExample",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonGeneratorExample",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonHttpClient",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonParserExample",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonServer",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonUdpBeacon",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/MsgPackParser",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/ProgmemExample",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/StringExample"
      ],
      "provides_includes": [
        "ArduinoJson.h",
        "ArduinoJson.hpp"
      ]
    },
    "release": {}
  },
  {
    "library": {
      "name": "wm8978-esp32",
      "author": "Cellie \u003cCelliesProjects@users.noreply.github.com\u003e",
      "maintainer": "Cellie \u003cCelliesProjects@users.noreply.github.com\u003e",
      "sentence": "An esp32 library for the wm8978 dac.",
      "paragraph": "Easy setup for the wm8978 dac with configurable i2c and i2s interfaces. With configurable MCLK on every PWM capable pin.",
      "website": "https://github.com/CelliesProjects/wm8978-esp32/",
      "category": "Signal Input/Output",
      "architectures": [
        "esp32"
      ],
      "install_dir": "/home/alien/Arduino/libraries/wm8978-esp32",
      "source_dir": "/home/alien/Arduino/libraries/wm8978-esp32/src",
      "real_name": "wm8978-esp32",
      "version": "1.0.0",
      "license": "Unspecified",
      "location": 1,
      "layout": 1,
      "examples": [
        "/home/alien/Arduino/libraries/wm8978-esp32/examples/M5Stack_wm8978"
      ],
      "provides_includes": [
        "WM8978.h"
      ]
    },
    "release": {}
  }
]
```

This instead is `lib list -b arduino:samd:mkr1000 --format json`:

```
[
  {
    "library": {
      "name": "ArduinoJson",
      "author": "Benoit Blanchon \u003cblog.benoitblanchon.fr\u003e",
      "maintainer": "Benoit Blanchon \u003cblog.benoitblanchon.fr\u003e",
      "sentence": "A simple and efficient JSON library for embedded C++.",
      "paragraph": "ArduinoJson supports ✔ serialization, ✔ deserialization, ✔ MessagePack, ✔ fixed allocation, ✔ zero-copy, ✔ streams, ✔ filtering, and more. It is the most popular Arduino library on GitHub ❤❤❤❤❤. Check out arduinojson.org for a comprehensive documentation.",
      "website": "https://arduinojson.org/?utm_source=meta\u0026utm_medium=library.properties",
      "category": "Data Processing",
      "architectures": [
        "*"
      ],
      "install_dir": "/home/alien/Arduino/libraries/ArduinoJson",
      "source_dir": "/home/alien/Arduino/libraries/ArduinoJson/src",
      "real_name": "ArduinoJson",
      "version": "6.16.1",
      "license": "MIT",
      "location": 1,
      "layout": 1,
      "examples": [
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonConfigFile",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonFilterExample",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonGeneratorExample",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonHttpClient",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonParserExample",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonServer",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/JsonUdpBeacon",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/MsgPackParser",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/ProgmemExample",
        "/home/alien/Arduino/libraries/ArduinoJson/examples/StringExample"
      ],
      "provides_includes": [
        "ArduinoJson.h",
        "ArduinoJson.hpp"
      ],
      "compatible_with": {
        "arduino:samd:mkr1000": true
      }
    },
    "release": {}
  }
]
```

Remember that the json doesn't reflect the gRPC interface but the CLI output, incompatible libraries are still included in the gRPC response but are marked as incompatible.

**Review by ubidefeo — APPROVED** [review]
works as expected

**Pull request merged**
