### PR TITLE
Add "permission denied" FAQ entry

### PR DESCRIPTION
**Pull request by wilyJ80**
Given the 50+ results for this "permission denied" error when uploading a sketch to the board in the forum, this entry was added to the FAQ. This might be desirable to have in an easily accessible page given it's a necessary step to take to get started with the microcontroller.

## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [ ] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

### CODE REVIEW

**Comment by matthijskooijman** [comment]
Looks good to document this. I would suggest:
 - Making it a bit clearer that this works on Linux
 - Clarify that this command works on *most* Linux distributions, but the exact command (group name) might be different on differnet distros (maybe also add an `ls -l /dev/ttyACM0` command or so to help people figure out the command they need.
 - Maybe adding a command `id | grep dialout` or `cat /dev/ttyACM0` they can use to verify if this is actually the problem and this fix is appropriate.

I realize that adding all these things might result in hairy and hard-to-read FAQ entry, so maybe not everything should be added (or maybe you can find a wording and structure that balances readability and completeness...).

**Comment by wilyJ80** [comment]
Pushed some changes. Tried to keep things concise but still reliable as suggested. Thanks for the suggestions, I'm learning more and more about the software side of Arduino.

**Comment by alessio-perugini** [comment]
@wilyJ80 Thank you for opening this. I see that it was committed the compiled binary in https://github.com/arduino/arduino-cli/pull/2564/commits/b41effc1ffb637334b865012bd4db10ffe1e1cfa do you mind removing it?

**Comment by wilyJ80** [comment]
Removed the binary directory. Is it OK now? Thank you for the patience. I'm starting out with contributing with this community. :smile:

**Review by alessio-perugini — APPROVED** [review]

**Comment by alessio-perugini** [comment]
@wilyJ80 Yup, thank you for bearing with us! :smile:

**Comment by matthijskooijman** [comment]
Hm, I'm a bit late to the party, but the documentation now just says "your group name", without any reference to how to figure out this group name, which is probably not very actionable for most users. I would suggest to use `dialout` in the example commandline and then say something like "The group name must be the owning group of the serial port (e.g. `/dev/ttyACM0`), on most Linux distributions it is `dialout`"

**Comment by alessio-perugini** [comment]
@matthijskooijman Oops, I missed that it was later changed into `<group>` somehow I managed to still read it with `dialout`. 
@wilyJ80 if you don't mind I'd open a quick PR adding the suggestion of @matthijskooijman .
Sorry about that :pray: , I guess I have to change my :eyeglasses:

**Pull request merged**
