### PR TITLE
[BREAKING] feat: added details to all init errors

### PR DESCRIPTION
**Pull request by Bikappa**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

## What kind of change does this PR introduce?

Iterates on #2076 adding details to more errors in the instance initialization flow

## What is the current behavior?

One case of index loading error and some other error scenarios do not have details
```
{
  "error": {
    "code": 9,
    "message": "Loading index file: reading library_index.json: open /Users/a.kitta/Library/Arduino15/library_index.json: no such file or directory"
  }
}
```

Platform loading errors are not reported as initialization errors
```
{
  "error": {
    "code": 9,
    "message": "Error loading hardware platform: discovery builtin:mdns-discovery not found",
    "details": [
      {"@type":"type.googleapis.com/cc.arduino.cli.commands.v1.PlatformLoadingError"}
    ]
  }
}
```

## What is the new behavior?

All init errors have a the corresponding details
```
{
  "error": {
    "code": 9,
    "message": "Loading index file: reading library_index.json: open /Users/bikappa/Library/Arduino15/library_index.json: no such file or directory"
   "details": [
         {"@type":"type.googleapis.com/cc.arduino.cli.commands.v1.FailedInstanceInitError", "message":"Loading index file: reading library_index.json: open /Users/bikappa/Library/Arduino15/library_index.json: no such file or directory","reason":"FAILED_INSTANCE_INIT_REASON_INDEX_LOAD_ERROR"
    ]
  }
}
```

Platform errors are wrapped into init errors and given a dedicated reason
```
{
  "error": {
    "code": 9,
    "message": "Error loading hardware platform: discovery builtin:serial-discovery not found",
    "details": [
      {"@type":"type.googleapis.com/cc.arduino.cli.commands.v1.FailedInstanceInitError", "message": "Error loading hardware platform: discovery builtin:serial-discovery not found", "reason": "FAILED_INSTANCE_INIT_REASON_PLATFORM_LOAD_ERROR"}
    ]
  }
}
```

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

Yes,`PlatformLoadingError` disappear as gprc type. Initialization errors related to platform loads now are have a detail of type `FailedInstanceInitError` as in the example above.

## Other information

Relates to https://github.com/arduino/arduino-cli/issues/1762

### CODE REVIEW

**Comment by kittaakos** [comment]
@Bikappa, could you please rebase the PR from the `master`? On IDE2's side, I need this change but also need https://github.com/arduino/arduino-cli/pull/2102 to have zero compiler errors. Thank you!

**Review by kittaakos — CHANGES_REQUESTED** [review]
Thank you!

Two things still need to be fixed. When the `library_index.json` is missing, IDE2 expects `reason` to be `FAILED_INSTANCE_INIT_REASON_LIBRARY_LOAD_ERROR` (`4`), but it isn't. All errors when deleting the `directories.data` location and initializing the gRPC client.

```json
[
    {
        "reason": 2,
        "message": "Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/package_index.json: open /Users/a.kitta/Library/Arduino15/package_index.json: no such file or directory"
    },
    {
        "reason": 2,
        "message": "Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/package_esp8266com_index.json: open /Users/a.kitta/Library/Arduino15/package_esp8266com_index.json: no such file or directory"
    },
    {
        "reason": 2,
        "message": "Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/package_esp32_index.json: open /Users/a.kitta/Library/Arduino15/package_esp32_index.json: no such file or directory"
    },
    {
        "reason": 2,
        "message": "Loading index file: loading json index file /Users/a.kitta/Library/Arduino15/package_teensy_index.json: open /Users/a.kitta/Library/Arduino15/package_teensy_index.json: no such file or directory"
    },
    {
        "reason": 5,
        "message": "discovery builtin:serial-discovery not found"
    },
    {
        "reason": 5,
        "message": "discovery builtin:mdns-discovery not found"
    },
    {
        "reason": 2,
        "message": "Loading index file: reading library_index.json: open /Users/a.kitta/Library/Arduino15/library_index.json: no such file or directory"
    }
]
```

From the errors 👆, IDE2 does not know if primary package index loading has failed or if it's a 3rd party platform.

**Comment by kittaakos** [comment]
> the error code has been updated to be the one you expect.

Thank you, @Bikappa

> I also don't know if we really want to maintain that.

IDE2 needs to decide somehow.

> propose to merge this as-is now

Sure, I will discard my review, and you can proceed with the merge. On the other hand, IDE2 would be the only client of this API but cannot use it, so merging this PR does not change anything.

> common error source design that provides structured metadata for non-human clients. For example:

IDE2 has been waiting for this since day one. I am sure there could be a more sophisticated way of propagating application-specific errors between IDE2 and CLI, but surely adding another enum type `FAILED_INSTANCE_INIT_REASON_INDEX_LOAD_ERROR` -> `FAILED_INSTANCE_INIT_REASON_PRIMARY_INDEX_LOAD_ERROR` seems a lot easier to indicate what has done wrong.

**Comment by cmaglie** [comment]
> From the errors point_up_2, IDE2 does not know if primary package index loading has failed or if it's a 3rd party platform.

I think this will be solved when we fix https://github.com/arduino/arduino-cli/issues/1529: it basically requires that the first `Init` call will trigger an index-update if the main index is missing, this would offload the IDE from the duty of understanding the reason of the failure and triggering an update on his own.

**Comment by cmaglie** [comment]
#1529 should have made the Init process much simpler and removed the need for most of the error code exposed here.

**Pull request closed without merging**
